### PR TITLE
fixes #165 - crash exporting an array with undefined as the first element

### LINKED ISSUE #165: Crash on export array with undefined/null values
Example:
```
vm := otto.New()
vm.Run(`var arr = [undefined, null]`)
arr, _ := vm.Get("arr")
arr.Export()
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x529400]

goroutine 1 [running]:
panic(0x6c3720, 0xc82000a150)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/robertkrimen/otto.Value.export(0x5, 0x6fdb80, 0xc820121a40, 0x0, 0x0)
	/home/bas/Development/golang/src/github.com/robertkrimen/otto/value.go:694 +0xba0
github.com/robertkrimen/otto.Value.Export(0x5, 0x6fdb80, 0xc820121a40, 0x0, 0x0, 0x0, 0x0)
	/home/bas/Development/golang/src/github.com/robertkrimen/otto/value.go:648 +0x4d
main.main()
	/home/bas/Development/golang/src/github.com/bas-vk/test/main.go:11 +0xef
exit status 2
```
With `vm.Set(...)` it works as expected.

### PR DESCRIPTION
**Pull request by deoxxa**

### CODE REVIEW

File: value.go [hunk 1]
```diff
@@ -690,7 +690,9 @@ func (self Value) export() interface{} {
 				}
 				value := object.get(name).export()
 				t = reflect.TypeOf(value)
-				if state == 0 {
+				if t == nil {
```
Comment (stevenh) [inline value.go]: This looks like it would prevent common type for nil?

Would this make more sense:
```go
var k reflect.Kind
if t != nil {
	k = t.Kind()
}
if state == 0 {
	kind = k
	state = 1
} else if state == 1 && kind != k {
       	state = 2
}
```

**Comment by stevenh** [comment]
As style thing with PR's a short title which doesn't wrap and then a description with detail is better  ;-)

File: value.go (hunk 1 above)
Comment (deoxxa) [inline value.go]: That still crashes later on, at the `Convert to the common type` point.

Comment (deoxxa) [inline value.go]: I've added an extra check for `t` being `nil` (which happens when `value` comes from `undefined`) before constructing the common type result, and this prevents that later crash.
